# SPDX-FileCopyrightText: 2026 Edgar Gomes de Araujo <talktoedgar@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  pages: write
  id-token: write

jobs:
  CI:
    uses: beam-bots/.github/.github/workflows/elixir-ci.yml@1563a9c56187b806c53a851ea6a72bad893e80e1 # main
    with:
      enable-docs-deploy: true
      enable-release: true
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
